name: book_doc
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.10+1
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  phone_text_field: ^0.0.7
  dartz: ^0.10.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  device_info_plus: ^10.1.2
  cached_network_image: ^3.4.0
  intl: ^0.19.0
  hydrated_bloc: ^9.1.5
  flutter_localization: ^0.2.2
  intl_phone_number_input: ^0.7.4
  intl_utils: ^2.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
flutter_intl:
  enabled: true
